#!/usr/bin/env python3
"""MuJoCo validation of navigation -> pre-contact -> front-board coverage."""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration


def generate_launch_description():
    wipe_share = get_package_share_directory('wipe_planner')
    mujoco_share = get_package_share_directory('tracer_jaka_mujoco')
    grid_map_share = get_package_share_directory('grid_map')
    bringup_share = get_package_share_directory('tracer_jaka_bringup')

    pipeline = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            bringup_share, 'launch', 'wipe_sim.launch.py')),
        launch_arguments={
            'viewer': LaunchConfiguration('viewer'),
            'use_rviz': LaunchConfiguration('use_rviz'),
            'start_slam': 'false',
            'auto_goal': LaunchConfiguration('auto_goal'),
            'wipe_task_file': LaunchConfiguration('wipe_task_file'),
            'mujoco_model': LaunchConfiguration('mujoco_model'),
            # The MuJoCo scene contains the real whiteboard, so REMANI must
            # plan in an ESDF that also contains it (generated from the same
            # scene by grid_map/mjcf_to_esdf.py) instead of the all-free
            # default; the base then cannot drive through the board plane.
            'remani_static_esdf_file': LaunchConfiguration(
                'remani_static_esdf_file'),
            'remani_max_consecutive_planning_failures': LaunchConfiguration(
                'remani_max_consecutive_planning_failures'),
            'force_control_enabled': 'false',
            # Do not let the task controller take over merely because the base
            # and yaw have reached the terminal region.  MuJoCo must reach and
            # hold the complete 9D pre-contact state first.
            'navigation_partial_handoff_enabled': 'false',
            'navigation_whole_body_squared_tolerance': '0.02',
            'navigation_arrival_hold': '0.50',
        }.items(),
    )

    return LaunchDescription([
        DeclareLaunchArgument('viewer', default_value='true'),
        DeclareLaunchArgument('use_rviz', default_value='true'),
        DeclareLaunchArgument('auto_goal', default_value='true'),
        DeclareLaunchArgument(
            'wipe_task_file',
            default_value=os.path.join(
                wipe_share, 'config', 'wipe_task_real_front.yaml')),
        DeclareLaunchArgument(
            'mujoco_model',
            default_value=os.path.join(
                mujoco_share, 'models', 'scene_wipe_front_board.xml')),
        DeclareLaunchArgument(
            'remani_static_esdf_file',
            default_value=os.path.join(
                grid_map_share, 'maps', 'front_board_esdf.npz'),
            description=(
                'Static ESDF generated by grid_map/mjcf_to_esdf.py from '
                'scene_wipe_front_board.xml, so REMANI navigation avoids '
                'driving through the whiteboard.')),
        DeclareLaunchArgument(
            'remani_max_consecutive_planning_failures', default_value='20',
            description=(
                'Consecutive REMANI search failures before returning to '
                'WAIT_TARGET. Lower this only for failure-path testing.')),
        pipeline,
    ])
